var myName="Satyavan Shejal";
console.log("The value of variable name is:",myName);
console.log("The Type  of variable name is:",typeof myName);
var age=26;
console.log("The value of variable age is:",age);
console.log("The Type  of variable age is:",typeof age);
var isMarried=true;
console.log("The value of variable isMarried is:",isMarried);
console.log("The Type  of variable isMarried is:",typeof isMarried);
console.log("Null Defination ",'Null is data type  which hold empty value ');
console.log("Undefined Defination ",'Undefined is data type  which hold undefined  value ');