console.log(`................Pre Increment....................`);
var index=10;
var y=++index;
console.log(`index: ${index}  y: ${y}`);
console.log(`......................POst Increment....................`);
var index=10;
var y=index++;
console.log(`index: ${index}  y: ${y}`);
console.log(`......................Pre Decrement....................`);
var index=10;
var y=++index;
console.log(`index: ${index}  y: ${y}`);
console.log(`......................POst Decrement....................`);
var index=10;
var y=index--;
console.log(`index: ${index}  y: ${y}`);